stages:
  - build

image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_REPO: 'luisnabais/gitlab-runner'
  BUILDX_VERSION: "v0.8.2"
  BUILDX_URL: "https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64"
  BUILDX_PLATFORMS: "linux/amd64,linux/arm64/v8"


docker-build:
  stage: build
  before_script:
    - wget -O /usr/bin/docker-buildx ${BUILDX_URL}
    - chmod +x /usr/bin/docker-buildx
    - docker login -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
    - IMAGE_TAG=$(grep 'FROM' Dockerfile | cut -d':' -f2)
  script:
    - docker-buildx create --use
    - docker buildx build
      --platform ${BUILDX_PLATFORMS}
      --tag ${DOCKER_REPO}:latest
      --tag ${DOCKER_REPO}:${IMAGE_TAG}
      --push
      .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - Dockerfile